services:
  mysql-dev:
    image: mysql:8
    container_name: mysql-dev-container
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: dev_db
    ports:
      - "3309:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql-dev" ]
      interval: 60s
      timeout: 20s
      retries: 10
    restart: always

  mysql-prod:
    image: mysql:8
    container_name: mysql-prod-container
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: prod_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_data_prod:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql-prod" ]
      interval: 60s
      timeout: 20s
      retries: 10
    restart: always

  app:
    build: .
    container_name: springboot-app
    depends_on:
      - mysql-dev
      - mysql-prod
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_DEV_URL: ${SPRING_DATASOURCE_DEV_URL}
      SPRING_DATASOURCE_DEV_USERNAME: ${SPRING_DATASOURCE_DEV_USERNAME}
      SPRING_DATASOURCE_DEV_PASSWORD: ${SPRING_DATASOURCE_DEV_PASSWORD}
      SPRING_DATASOURCE_PROD_URL: ${SPRING_DATASOURCE_PROD_URL}
      SPRING_DATASOURCE_PROD_USERNAME: ${SPRING_DATASOURCE_PROD_USERNAME}
      SPRING_DATASOURCE_PROD_PASSWORD: ${SPRING_DATASOURCE_PROD_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file: .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    env_file: .env

volumes:
  mysql_data_dev:
  mysql_data_prod:
networks:
  app-network:
    driver: bridge
