services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: springboot-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_DEV_URL: ${SPRING_DATASOURCE_DEV_URL}
      SPRING_DATASOURCE_DEV_USERNAME: ${SPRING_DATASOURCE_DEV_USERNAME}
      SPRING_DATASOURCE_DEV_PASSWORD: ${SPRING_DATASOURCE_DEV_PASSWORD}
      SPRING_DATASOURCE_PROD_URL: ${SPRING_DATASOURCE_PROD_URL}
      SPRING_DATASOURCE_PROD_USERNAME: ${SPRING_DATASOURCE_PROD_USERNAME}
      SPRING_DATASOURCE_PROD_PASSWORD: ${SPRING_DATASOURCE_PROD_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"

volumes:
  mysql_data:
