
services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: .env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 60s
      timeout: 20s
      retries: 10


  app:
    build: .
    container_name: springboot-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_DEV_URL: ${SPRING_DATASOURCE_DEV_URL}
      SPRING_DATASOURCE_DEV_USERNAME: ${SPRING_DATASOURCE_DEV_USERNAME}
      SPRING_DATASOURCE_DEV_PASSWORD: ${SPRING_DATASOURCE_DEV_PASSWORD}
      SPRING_DATASOURCE_PROD_URL: ${SPRING_DATASOURCE_PROD_URL}
      SPRING_DATASOURCE_PROD_USERNAME: ${SPRING_DATASOURCE_PROD_USERNAME}
      SPRING_DATASOURCE_PROD_PASSWORD: ${SPRING_DATASOURCE_PROD_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file: .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    env_file: .env
volumes:
  mysql_data:
