spring:
  config:
    activate:
      on-profile: ${SPRING_PROFILES_ACTIVE:dev}

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://mysql:3306/dev_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://mysql:3306/prod_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root_password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

---

spring:
  config:
    activate:
      on-profile: sit

  datasource:
    url: jdbc:mysql://mysql:3306/sit_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
